name: padyatra
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^1.0.4
  finite_coverflow: ^1.0.0
  introduction_screen: ^1.0.9
  simple_animations: ^2.2.1
  location: ^3.0.2
  google_maps_flutter: ^0.5.3
  toast: ^0.1.5
  fluttertoast: ^7.1.1
  geofence_flutter: ^1.1.0
  shared_preferences: ^0.5.12+4
  url_launcher: ^6.0.3
  flutter_spinkit: ^5.0.0
  image_picker: ^0.6.6+1
  cupertino_icons: ^0.1.3
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/
    - images/hike3.png
    - images/hiker.png
    - images/login.jpg
    - images/signup_top.png
    - images/Interest1.jpg
    - images/hike1.jpg
    - images/journey-concept.jpg


  fonts:
  - family: Noto Sans
    fonts:
    - asset: fonts/NotoSans-Regular.ttf
  - family: Roboto
    fonts:
    - asset: fonts/Roboto-Regular.ttf
  - family: Playfair Display
    fonts:
    - asset: fonts/PlayfairDisplay-Regular.ttf
  - family: JosefinSans Regular
    fonts:
    - asset: fonts/JosefinSans-Regular.ttf
  - family: Oswald
    fonts:
    - asset: fonts/Oswald-Regular.ttf
  - family: JosefinSans Thin
    fonts:
    - asset: fonts/JosefinSans-thin.ttf
  - family: Lato
    fonts:
    - asset: fonts/Lato-Regular.ttf
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-SemiBold.ttf
