name: padyatra
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolor: 
  finite_coverflow: 
  introduction_screen: 
  simple_animations: ^2.2.1
  location: 
  google_maps_flutter: 
  toast: 
  fluttertoast: 
  geofence_flutter: 
  shared_preferences: 
  url_launcher: 
  flutter_spinkit: 
  image_picker: 
  cupertino_icons: 
  http: 

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/
    - images/hike3.png
    - images/hiker.png
    - images/login.jpg
    - images/signup_top.png
    - images/Interest1.jpg
    - images/hike1.jpg
    - images/journey-concept.jpg
    - images/No_Connection.png


  fonts:
  - family: Noto Sans
    fonts:
    - asset: fonts/NotoSans-Regular.ttf
  - family: Roboto
    fonts:
    - asset: fonts/Roboto-Regular.ttf
  - family: Playfair Display
    fonts:
    - asset: fonts/PlayfairDisplay-Regular.ttf
  - family: JosefinSans Regular
    fonts:
    - asset: fonts/JosefinSans-Regular.ttf
  - family: Oswald
    fonts:
    - asset: fonts/Oswald-Regular.ttf
  - family: JosefinSans Thin
    fonts:
    - asset: fonts/JosefinSans-thin.ttf
  - family: Lato
    fonts:
    - asset: fonts/Lato-Regular.ttf
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-SemiBold.ttf
